
version: '3'
services:

  db:
    image: postgres:latest
    restart: always
    container_name: postgres_cont
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: utyfull
      POSTGRES_PASSWORD: 1215010q
      PGDATA: db:/var/lib/postgres/data
    ports:
      - 127.0.0.1:5431:5432
    expose:
      - "5432"
    volumes:
     - db:/var/lib/postgresql/data
     - db:/var/lib/postgres/data -l logfile start
  adminer:
    container_name: adminer_cont
    image: adminer:latest
    restart: always
    ports:
     - 8080:8080
  
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis_cont
    environment:
      - REDIS_USER=utyfull
      - REDIS_PASSWORD=1215010q
      - REDIS_PORT=6379
    ports:
      - 127.0.0.1:6378:6379
    expose:
      - "6379"
    volumes:
      - redis:/data

     
volumes:
  db:
    driver: local
  pgadmin:
  redis:
    driver: local
